[workspace]
members = [
    "bolero",
    "bolero-*",
    "cargo-bolero",
]

[profile.fuzz]
inherits = "dev"
opt-level = 3
incremental = false
codegen-units = 1

[profile.release]
lto = true
codegen-units = 1
incremental = false
