[package]
name = "bolero-generator"
version = "0.1.1"
authors = ["Cameron Bytheway <bytheway.cameron@gmail.com>"]
description = "generational testing traits for bolero"
homepage = "https://github.com/camshaft/bolero"
repository = "https://github.com/camshaft/bolero"
keywords = ["testing", "fuzz"]
license = "MIT"
edition = "2018"

[features]
std = ["either/use_std"]

[dependencies]
byteorder = "1.3"
either = { version = "1.5", default-features = false }
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
