[package]
name = "bolero-generator"
version = "0.1.0"
authors = ["Cameron Bytheway <bytheway.cameron@gmail.com>"]
description = "generational testing traits for bolero"
homepage = "https://github.com/camshaft/bolero"
repository = "https://github.com/camshaft/bolero"
keywords = ["testing", "fuzz"]
license = "MIT"
edition = "2018"

[features]
std = []

[dependencies]
byteorder = "1.3"
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
