[package]
name = "bolero-generator"
version = "0.1.0"
authors = ["Cameron Bytheway <bytheway.cameron@gmail.com>"]
edition = "2018"

[features]
std = []

[dependencies]
byteorder = "1.3"
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
