[package]
name = "bolero"
version = "0.1.0"
authors = ["Cameron Bytheway <bytheway.cameron@gmail.com>"]
edition = "2018"

[dependencies]
backtrace = "0.3"
bolero-generator = { path = "../bolero-generator" }
bolero-libfuzzer = { path = "../bolero-libfuzzer" }
lazy_static = "1"
libtest-mimic = "0.1.0"
