[package]
name = "bolero"
version = "0.1.0"
authors = ["Cameron Bytheway <bytheway.cameron@gmail.com>"]
description = "fuzzing made easy"
homepage = "https://github.com/camshaft/bolero"
repository = "https://github.com/camshaft/bolero"
keywords = ["testing", "fuzz"]
license = "MIT"
edition = "2018"

[dependencies]
backtrace = "0.3"
bolero-afl = { version = "0.1", path = "../bolero-afl" }
bolero-generator = { version = "0.1", path = "../bolero-generator" }
bolero-libfuzzer = { version = "0.1", path = "../bolero-libfuzzer" }
cfg-if = "0.1"
lazy_static = "1"
libtest-mimic = "0.1.0"
