on: [push, pull_request]

name: Continuous integration

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        rust: [stable, beta, nightly]

    steps:
    - name: Ubuntu Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install binutils-dev libunwind-dev

    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
        components: rustfmt, clippy

    - uses: actions/checkout@master

    - name: Format
      if: matrix.os == 'ubuntu-latest' && matrix.rust == 'stable'
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - name: Clippy
      if: matrix.os == 'ubuntu-latest' && matrix.rust == 'stable'
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings

    - name: Test
      run: make test
      env:
        AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES: 1
